  
dist: trusty

sudo: required

language: go

go: '1.13.x'

script:
  - go build
      
notifications:
  email:
    recipients:
      - asharnrus.info@gmail.com
    on_success: never
    on_failure: always