name: "LazyMechanic"
version: "1.0.0"
author: "LazyMechanic"
description: "Preset with CI config templates, clang format settings and readme"
variables:
  - key: "enable_version_name"
    description: "Enable or disable extensions"
    value_pattern: "ON|OFF"
    default: "OFF"
    storages:
      - executable
  - key: "lang"
    description: "Set language"
    value_pattern: "CXX|C"
    default: "CXX"
    storages:
      - executable
      - library
      - interface
      - test
      - project
  - key: "lang_standard"
    description: "Set language standard"
    value_pattern: "^[0-9]+$"
    default: "17"
    storages:
      - executable
      - library
      - interface
      - test
  - key: "lang_extensions"
    description: "Enable or disable extensions. For example GCC extensions"
    value_pattern: "ON|OFF"
    default: "OFF"
    storages:
      - executable
      - library
      - interface
      - test
  - key: "lang_standard_required"
    description: "Enable or disable standard requiring"
    value_pattern: "ON|OFF"
    default: "ON"
    storages:
      - executable
      - library
      - interface
      - test